build_from:
  aarch64: ghcr.io/alams154/music-assistant-alexa-api:latest
  amd64: ghcr.io/alams154/music-assistant-alexa-api:latest
  armhf: ghcr.io/alams154/music-assistant-alexa-api:latest
  armv7: ghcr.io/alams154/music-assistant-alexa-api:latest
  i386: ghcr.io/alams154/music-assistant-alexa-api:latest
